[package]
name = "pfs-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
folder = "0.5.0"
pathdiff = "0.2.1"
rayon = "1.8.0"
sha1 = "0.10.6"
